# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e9be16a5dda6a9725868d3141d71b3218669bc91dc8df362f2e19b26d172d98ad090db901020d647cc8a3f5b7010da3de840f3a0026180f12788c95b87c3c897

test:
  secret_key_base: 858cff9d2fea7567e41d8c460aad21670e6e40b1abfe9867a8b2a3a221a880c035e12b1facd8ec92cf5af853111a6c25c4faa772952873ea02a4b16bef0959aa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
